import React from 'react';
import '@testing-library/jest-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import { StructurePageConsolidated } from '../../src/components/zion/StructurePageConsolidated.jsx';

let mockStore = {};
const noop = vi.fn();

vi.mock('../../src/state/identityStore', () => ({
  useIdentityStore: () => mockStore,
}));

function buildStore() {
  const cycleId = 'cycle-1';
  const goalId = 'goal-1';
  return {
    activeCycleId: cycleId,
    cyclesById: {
      [cycleId]: {
        id: cycleId,
        status: 'active',
        goalContract: { goalId, startDayKey: '2026-03-01', endDayKey: '2026-04-01' },
        executionEvents: [],
      },
    },
    goalExecutionContract: { goalId, startDayKey: '2026-03-01', endDayKey: '2026-04-01' },
    aspirations: [],
    appTime: { activeDayKey: '2026-03-10', nowISO: '2026-03-10T12:00:00.000Z', timeZone: 'UTC' },
    proposedBlocks: [],
    suggestedBlocks: [
      { id: 'legacy-1', cycleId, goalId, status: 'suggested' },
      { id: 'legacy-2', cycleId, goalId, status: 'suggested' },
    ],
    lastPlanError: null,
    deliverablesByCycleId: {
      [cycleId]: {
        cycleId,
        autoGenerated: true,
        autoStrategy: { detectedType: 'generic' },
        suggestionLinks: {},
        deliverables: [{ id: 'd1', title: 'Planning & setup', requiredBlocks: 4 }],
      },
    },
    goalAdmissionByGoal: {},
    updateWorkWindows: noop,
    attemptGoalAdmission: noop,
  };
}

describe('Structure legacy fallback guard', () => {
  beforeEach(() => {
    mockStore = buildStore();
  });

  it('does not surface stale suggestedBlocks count when canonical proposedBlocks are present as empty', () => {
    render(<StructurePageConsolidated />);
    expect(screen.queryByText(/proposed calendar blocks/i)).not.toBeInTheDocument();
    expect(screen.getByText(/no schedule proposal yet\. go to today tab to generate\./i)).toBeInTheDocument();
  });
});
