import React from 'react';
import '@testing-library/jest-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import { StructurePageConsolidated } from '../../src/components/zion/StructurePageConsolidated.jsx';

let mockStore = {};
const noop = vi.fn();

vi.mock('../../src/state/identityStore', () => ({
  useIdentityStore: () => mockStore,
}));

function baseStore(deliverables, autoStrategy = null, options = {}) {
  const cycleId = 'cycle-1';
  const goalId = 'goal-1';
  return {
    activeCycleId: cycleId,
    cyclesById: {
      [cycleId]: {
        id: cycleId,
        status: 'active',
        goalContract: { goalId, startDayKey: '2026-03-01', endDayKey: '2026-04-01' },
        executionEvents: [],
        scheduleReviewBlocks: options.scheduleReviewBlocks || [],
        actions: options.actions || [],
        ...(options.planQualityGate ? { planQualityGate: options.planQualityGate } : {}),
      },
    },
    goalExecutionContract: { goalId, startDayKey: '2026-03-01', endDayKey: '2026-04-01' },
    aspirations: [],
    appTime: { activeDayKey: '2026-03-10', nowISO: '2026-03-10T12:00:00.000Z', timeZone: 'UTC' },
    proposedBlocks: options.proposedBlocks || [],
    suggestedBlocks: options.suggestedBlocks || [],
    lastPlanError: null,
    deliverablesByCycleId: {
      [cycleId]: {
        cycleId,
        autoGenerated: Boolean(autoStrategy),
        autoStrategy,
        suggestionLinks: {},
        deliverables,
      },
    },
    goalAdmissionByGoal: {},
    planQualityGateByGoal: options.planQualityGate ? { [goalId]: options.planQualityGate } : {},
    updateWorkWindows: noop,
    attemptGoalAdmission: noop,
  };
}

describe('Structure deliverable terminology contract', () => {
  beforeEach(() => {
    mockStore = baseStore([]);
  });

  it('uses phase terminology when displayed items are generic phase/group labels', () => {
    mockStore = baseStore(
      [
        { id: 'd1', title: 'Planning & setup', requiredBlocks: 3 },
        { id: 'd2', title: 'Core production', requiredBlocks: 3 },
        { id: 'd3', title: 'Verification & finalization', requiredBlocks: 2 },
      ],
      { detectedType: 'generic' }
    );
    render(<StructurePageConsolidated />);
    expect(screen.getByText(/plan sections \(3\)/i)).toBeInTheDocument();
    expect(screen.queryByText(/^deliverables$/i)).not.toBeInTheDocument();
  });

  it('uses deliverable terminology when displayed items are concrete outputs', () => {
    mockStore = baseStore([
      { id: 'd1', title: 'Completed practice exam set', requiredBlocks: 3 },
      { id: 'd2', title: 'Exam registration submitted', requiredBlocks: 1 },
    ]);
    render(<StructurePageConsolidated />);
    expect(screen.getByText(/deliverable outputs \(2\)/i)).toBeInTheDocument();
  });

  it('renders a formal chart linking deliverables to scheduled blocks and action lineage', () => {
    mockStore = baseStore(
      [
        { id: 'd1', title: 'Portfolio project 1 dashboard', requiredBlocks: 2 },
        { id: 'd2', title: 'Portfolio project 2 SQL analysis', requiredBlocks: 1 },
      ],
      null,
      {
        actions: [
          { id: 'a1', title: 'Scope dashboard questions' },
          { id: 'a2', title: 'Build SQL query set' },
        ],
        scheduleReviewBlocks: [
          {
            id: 'b1',
            deliverableId: 'd1',
            actionId: 'a1',
            title: 'Define success criteria for portfolio-quality dashboard',
            start: '2026-03-10T14:00:00.000Z',
          },
        ],
      }
    );

    render(<StructurePageConsolidated />);

    expect(screen.getByText(/formal plan chart/i)).toBeInTheDocument();
    expect(screen.getByText(/1 scheduled block/i)).toBeInTheDocument();
    expect(screen.getAllByText('Portfolio project 1 dashboard').length).toBeGreaterThan(0);
    expect(screen.getByText('Define success criteria for portfolio-quality dashboard')).toBeInTheDocument();
    expect(screen.getByText('Scope dashboard questions')).toBeInTheDocument();
    expect(screen.getByText(/currently have no scheduled blocks/i)).toBeInTheDocument();
  });

  it('renders generated proposed blocks on the formal chart before apply', () => {
    mockStore = baseStore(
      [
        { id: 'd1', title: 'Pitch deck and narrative package', requiredBlocks: 2, actionIds: ['a1'] },
        { id: 'd2', title: 'Investor list and fit scoring model', requiredBlocks: 1 },
      ],
      null,
      {
        actions: [
          { id: 'a1', title: 'Pitch narrative action' },
          { id: 'a2', title: 'Score target investors by fit and warmth' },
        ],
        proposedBlocks: [
          {
            id: 'pb-1',
            cycleId: 'cycle-1',
            goalId: 'goal-1',
            deliverableId: 'd1',
            actionId: 'a1',
            title: 'Draft investor-ready pitch deck storyline',
            startISO: '2026-03-10T14:00:00.000Z',
            status: 'suggested',
          },
          {
            id: 'pb-other-cycle',
            cycleId: 'cycle-2',
            goalId: 'goal-2',
            deliverableId: 'd1',
            actionId: 'a1',
            title: 'Stale block from another cycle',
            startISO: '2026-03-11T14:00:00.000Z',
            status: 'suggested',
          },
        ],
      }
    );

    render(<StructurePageConsolidated />);

    expect(screen.getByText(/formal plan chart/i)).toBeInTheDocument();
    expect(screen.getByText(/1 scheduled block/i)).toBeInTheDocument();
    expect(screen.getByText('Draft investor-ready pitch deck storyline')).toBeInTheDocument();
    expect(screen.getAllByText('Pitch deck and narrative package').length).toBeGreaterThan(1);
    expect(screen.getByText('Pitch narrative action')).toBeInTheDocument();
    expect(screen.queryByText(/0 scheduled blocks across/i)).not.toBeInTheDocument();
    expect(screen.queryByText('Stale block from another cycle')).not.toBeInTheDocument();
  });

  it('surfaces canonical long-horizon tail-gap diagnostics in Structure', () => {
    mockStore = baseStore(
      [{ id: 'd1', title: 'Jericho v1 launch validation', requiredBlocks: 5, actionIds: ['a1'] }],
      null,
      {
        actions: [{ id: 'a1', title: 'Validate Jericho v1 launch path', deliverableId: 'd1' }],
        planQualityGate: {
          status: 'PLAN_QUALITY_WITHHELD',
          failureCodes: ['LONG_HORIZON_UNJUSTIFIED_TAIL_GAP'],
          reasonCodes: ['LONG_HORIZON_UNJUSTIFIED_TAIL_GAP'],
          meta: {
            temporalDistribution: {
              contractStartDayKey: '2026-04-13',
              contractEndDayKey: '2027-04-12',
              firstScheduledDayKey: '2026-04-20',
              lastScheduledDayKey: '2026-11-09',
              horizonDays: 365,
              scheduledSpanDays: 204,
              occupiedMonths: ['2026-04', '2026-06', '2026-08', '2026-09', '2026-11'],
              latestScheduledHorizonRatio: 0.57,
              requiredLatestHorizonRatio: 0.67,
              requiredOccupiedMonths: 7,
              remainingTailDays: 154,
              remainingTailRatio: 0.42,
              maxUnjustifiedTailRatio: 0.25,
            },
          },
        },
      }
    );

    render(<StructurePageConsolidated />);

    expect(screen.getByText(/Plan-quality diagnostics/i)).toBeInTheDocument();
    expect(screen.getByText(/PLAN QUALITY WITHHELD/i)).toBeInTheDocument();
    expect(screen.getByText(/Long-horizon issue: work ends on 11\/09\/2026, leaving an unjustified tail before 04\/12\/2027\./i)).toBeInTheDocument();
    expect(screen.getByText(/large unexplained tail before the contract end/i)).toBeInTheDocument();
  });

  it('reconciles generated blocks to workspace deliverables by action lineage when draft deliverable ids drift', () => {
    mockStore = baseStore(
      [{ id: 'd1', title: 'Music release concept package', requiredBlocks: 2, actionIds: ['a1'] }],
      null,
      {
        actions: [{ id: 'a1', title: 'Capture tracklist, audience direction, and release concept' }],
        proposedBlocks: [
          {
            id: 'pb-drift',
            cycleId: 'cycle-1',
            goalId: 'goal-1',
            deliverableId: 'deliv-synthetic-1',
            actionId: 'a1',
            title: 'Capture tracklist, audience direction, and release concept for music release',
            startISO: '2026-03-10T14:00:00.000Z',
            status: 'suggested',
          },
        ],
      }
    );

    render(<StructurePageConsolidated />);

    expect(screen.getByText(/formal plan chart/i)).toBeInTheDocument();
    expect(screen.getByText(/1 scheduled block/i)).toBeInTheDocument();
    expect(
      screen.getByText('Capture tracklist, audience direction, and release concept for music release')
    ).toBeInTheDocument();
    expect(screen.getByText('Capture tracklist, audience direction, and release concept')).toBeInTheDocument();
    expect(screen.queryByText(/currently have no scheduled blocks/i)).not.toBeInTheDocument();
  });

  it('reconciles formal chart counts from canonical execution events when review blocks are empty', () => {
    mockStore = baseStore([{ id: 'd1', title: 'Business analysis query case study', requiredBlocks: 2 }], null, {
      actions: [{ id: 'a1', title: 'Answer business questions with SQL queries' }],
    });
    mockStore.cyclesById['cycle-1'].executionEvents = [
      {
        id: 'evt-1',
        blockId: 'blk-1',
        kind: 'create',
        completed: false,
        dateISO: '2026-03-12',
        minutes: 45,
        rawLabel: 'Answer business questions with cohort retention SQL queries',
        canonicalTitle: 'Answer business questions with cohort retention SQL queries',
        domain: 'Focus',
        cycleId: 'cycle-1',
        goalId: 'goal-1',
        deliverableId: 'd1',
        actionId: 'a1',
        startISO: '2026-03-12T14:00:00.000Z',
        endISO: '2026-03-12T14:45:00.000Z',
        status: 'planned',
      },
    ];

    render(<StructurePageConsolidated />);

    expect(screen.getByText(/formal plan chart/i)).toBeInTheDocument();
    expect(screen.getByText(/1 scheduled block/i)).toBeInTheDocument();
    expect(screen.getAllByText('Business analysis query case study').length).toBeGreaterThan(0);
    expect(screen.getByText('Answer business questions with cohort retention SQL queries')).toBeInTheDocument();
    expect(screen.getByText('Answer business questions with SQL queries')).toBeInTheDocument();
    expect(screen.queryByText(/currently have no scheduled blocks/i)).not.toBeInTheDocument();
  });

  it('prefers applied review blocks over proposed blocks during lifecycle transition without duplicating rows', () => {
    mockStore = baseStore([{ id: 'd1', title: 'Release checklist package', requiredBlocks: 1 }], null, {
      actions: [{ id: 'a1', title: 'Ship plan action lineage' }],
      proposedBlocks: [
        {
          id: 'pb-1',
          cycleId: 'cycle-1',
          goalId: 'goal-1',
          deliverableId: 'd1',
          actionId: 'a1',
          title: 'Draft release checklist proposal',
          startISO: '2026-03-10T14:00:00.000Z',
          status: 'suggested',
        },
      ],
      scheduleReviewBlocks: [
        {
          id: 'rb-1',
          cycleId: 'cycle-1',
          goalId: 'goal-1',
          deliverableId: 'd1',
          actionId: 'a1',
          title: 'Finalize release checklist and ship plan',
          start: '2026-03-10T15:00:00.000Z',
          status: 'planned',
        },
      ],
    });

    render(<StructurePageConsolidated />);

    expect(screen.getByText(/formal plan chart/i)).toBeInTheDocument();
    expect(screen.getByText(/1 scheduled block/i)).toBeInTheDocument();
    expect(screen.getByText('Finalize release checklist and ship plan')).toBeInTheDocument();
    expect(screen.getByText('Ship plan action lineage')).toBeInTheDocument();
    expect(screen.queryByText('Draft release checklist proposal')).not.toBeInTheDocument();
  });

  it('does not render stale chart blocks after the active cycle is removed', () => {
    mockStore = baseStore([{ id: 'd1', title: 'Deleted cycle deliverable', requiredBlocks: 1 }], null, {
      actions: [{ id: 'a1', title: 'Deleted cycle action lineage' }],
      proposedBlocks: [
        {
          id: 'pb-deleted',
          cycleId: 'cycle-1',
          goalId: 'goal-1',
          deliverableId: 'd1',
          actionId: 'a1',
          title: 'Stale deleted-cycle block',
          startISO: '2026-03-10T14:00:00.000Z',
          status: 'suggested',
        },
      ],
    });
    mockStore.activeCycleId = null;
    mockStore.cyclesById = {};
    mockStore.deliverablesByCycleId = {};
    mockStore.goalExecutionContract = null;

    render(<StructurePageConsolidated />);

    expect(screen.queryByText(/formal plan chart/i)).not.toBeInTheDocument();
    expect(screen.queryByText('Stale deleted-cycle block')).not.toBeInTheDocument();
  });

  it('surfaces semantic chart inspection data for action type, assumptions, readiness, and long titles', () => {
    mockStore = baseStore([{ id: 'd1', title: 'Investor-ready package', requiredBlocks: 3 }], null, {
      actions: [
        {
          id: 'a0',
          title: 'Confirm investor target list',
          actionType: 'preparation',
        },
        {
          id: 'a1',
          title: 'Draft long-form investor narrative and financial ask storyline',
          actionType: 'execution',
          dependencies: ['a0'],
          assumptions: ['financial model inputs are directionally correct'],
        },
      ],
      proposedBlocks: [
        {
          id: 'pb-1',
          cycleId: 'cycle-1',
          goalId: 'goal-1',
          deliverableId: 'd1',
          actionId: 'a1',
          title: 'Draft long-form investor narrative and financial ask storyline with use-of-funds explanation',
          startISO: '2026-03-10T14:00:00.000Z',
          status: 'suggested',
          assumption: 'investor questions remain within the current package scope',
        },
      ],
    });
    mockStore.cyclesById['cycle-1'].goalContract.goalIntakeContract = {
      readiness: {
        assumptionReasons: ['GOAL_TEXT_ASSUMED'],
      },
    };

    render(<StructurePageConsolidated />);

    expect(screen.getByRole('columnheader', { name: /required sessions/i })).toBeInTheDocument();
    expect(screen.getByRole('columnheader', { name: /scheduled blocks/i })).toBeInTheDocument();
    expect(
      screen.getByText('Draft long-form investor narrative and financial ask storyline with use-of-funds explanation')
    ).toBeInTheDocument();
    expect(screen.getByText('Draft long-form investor narrative and financial ask storyline')).toBeInTheDocument();
    expect(screen.getByText('Execution')).toBeInTheDocument();
    expect(screen.getByText(/depends on:\s*Confirm investor target list/i)).toBeInTheDocument();
    expect(screen.getByText(/Assumption:\s*financial model inputs are directionally correct/i)).toBeInTheDocument();
    expect(
      screen.getByText(/Assumption:\s*investor questions remain within the current package scope/i)
    ).toBeInTheDocument();
    expect(screen.getByText(/Plan assumptions \(1\)/i)).toBeInTheDocument();
    expect(screen.getByText(/Assumption:\s*GOAL_TEXT_ASSUMED/i)).toBeInTheDocument();
  });

  it('renders unknown action type when canonical actionType is missing instead of inventing certainty', () => {
    mockStore = baseStore([{ id: 'd1', title: 'Portfolio artifact', requiredBlocks: 1 }], null, {
      actions: [{ id: 'a1', title: 'Build portfolio artifact without action type metadata' }],
      proposedBlocks: [
        {
          id: 'pb-unknown',
          cycleId: 'cycle-1',
          goalId: 'goal-1',
          deliverableId: 'd1',
          actionId: 'a1',
          title: 'Build portfolio artifact without action type metadata',
          startISO: '2026-03-10T14:00:00.000Z',
          status: 'suggested',
        },
      ],
    });

    render(<StructurePageConsolidated />);

    expect(screen.getByText('Unknown')).toBeInTheDocument();
  });

  it('projects canonical full-horizon block type, owner, lineage, phase dependencies, and local scheduled time on the formal chart', () => {
    mockStore = {
      ...baseStore([{ id: 'masterplan-deliverable:lane-1', title: 'Operation Endgame app platform', requiredBlocks: 1 }]),
      appTime: { activeDayKey: '2026-03-10', nowISO: '2026-03-10T12:00:00.000Z', timeZone: 'America/Chicago' },
      selectedHorizonMode: 'full_horizon',
      fullHorizonScheduleBlocks: [
        {
          id: 'fh-1',
          deliverableId: 'masterplan-deliverable:lane-1',
          laneId: 'lane-1',
          laneLabel: 'Operation Endgame app platform',
          blockType: 'action',
          title: 'Implement retention loop improvement for Operation Endgame app platform using conversion threshold proof',
          displayTitle: 'Implement retention loop improvement for Operation Endgame app platform using conversion threshold proof',
          derivationReason: 'Derived from P2 conversion proof requirements for the product/software lane.',
          dependsOn: ['phase:P1'],
          owner: 'product_owner',
          startISO: '2026-03-10T14:00:00.000Z',
          start: '2026-03-10T14:00:00.000Z',
          durationMinutes: 60,
          status: 'planned',
          source: 'derived',
        },
      ],
    };

    render(<StructurePageConsolidated />);

    expect(screen.getByRole('columnheader', { name: /owner/i })).toBeInTheDocument();
    expect(screen.getByText('Execution')).toBeInTheDocument();
    expect(screen.getByText('Product Owner')).toBeInTheDocument();
    expect(screen.getByText(/Derived from P2 conversion proof requirements/i)).toBeInTheDocument();
    expect(screen.getByText(/Locked by phase prerequisite:\s*P1/i)).toBeInTheDocument();
    expect(screen.getByText(/09:00/i)).toBeInTheDocument();
    expect(screen.queryByText(/^Unknown$/i)).not.toBeInTheDocument();
    expect(screen.queryByText(/Dependency missing:\s*phase:P1/i)).not.toBeInTheDocument();
  });

  it('renders long-horizon temporal structure when canonical phase and pacing metadata are supportable', () => {
    mockStore = baseStore(
      [
        { id: 'd1', title: 'Preparation package', requiredBlocks: 2, actionIds: ['prep:001'] },
        { id: 'd2', title: 'Execution batch one', requiredBlocks: 2, actionIds: ['build:001'] },
        { id: 'd3', title: 'Execution batch two', requiredBlocks: 2, actionIds: ['build:002'] },
      ],
      null,
      {
        actions: [
          { id: 'prep:001', title: 'Prepare work', actionType: 'preparation' },
          { id: 'build:001', title: 'Execute work one', actionType: 'execution' },
          { id: 'build:002', title: 'Execute work two', actionType: 'execution' },
        ],
        proposedBlocks: [
          {
            id: 'pb-1',
            cycleId: 'cycle-1',
            goalId: 'goal-1',
            deliverableId: 'd1',
            actionId: 'prep:001',
            title: 'Prepare work',
            startISO: '2026-03-05T14:00:00.000Z',
            status: 'suggested',
          },
          {
            id: 'pb-2',
            cycleId: 'cycle-1',
            goalId: 'goal-1',
            deliverableId: 'd2',
            actionId: 'build:001',
            title: 'Execute work one',
            startISO: '2026-04-10T14:00:00.000Z',
            status: 'suggested',
          },
          {
            id: 'pb-3',
            cycleId: 'cycle-1',
            goalId: 'goal-1',
            deliverableId: 'd3',
            actionId: 'build:002',
            title: 'Execute work two',
            startISO: '2026-05-10T14:00:00.000Z',
            status: 'suggested',
          },
        ],
      }
    );
    mockStore.cyclesById['cycle-1'].goalContract = {
      ...mockStore.cyclesById['cycle-1'].goalContract,
      startDayKey: '2026-03-01',
      endDayKey: '2026-05-31',
    };
    mockStore.goalExecutionContract = {
      ...mockStore.goalExecutionContract,
      startDayKey: '2026-03-01',
      endDayKey: '2026-05-31',
    };
    mockStore.deliverablesByCycleId['cycle-1'].scaffoldGroups = [
      { id: 'phase-prep', title: 'Preparation', type: 'phase', actionIds: ['prep:001'], deliverableIds: ['d1'] },
      {
        id: 'phase-exec',
        title: 'Execution',
        type: 'phase',
        actionIds: ['build:001', 'build:002'],
        deliverableIds: ['d2', 'd3'],
      },
    ];

    render(<StructurePageConsolidated />);

    expect(screen.getByText(/long-horizon structure/i)).toBeInTheDocument();
    expect(screen.getAllByText('Preparation').length).toBeGreaterThan(0);
    expect(screen.getAllByText('Execution').length).toBeGreaterThan(0);
    expect(screen.getByText(/temporal certainty/i)).toBeInTheDocument();
    expect(screen.getByText(/firm/i)).toBeInTheDocument();
    expect(screen.getByText(/provisional/i)).toBeInTheDocument();
    expect(screen.getByText(/checkpoints/i)).toBeInTheDocument();
    expect(screen.getByText(/review preparation before execution/i)).toBeInTheDocument();
    expect(screen.getByText(/long-term quality/i)).toBeInTheDocument();
    expect(screen.getByText(/trusted/i)).toBeInTheDocument();
    expect(screen.getByText(/saturation/i)).toBeInTheDocument();
    expect(screen.getByText(/pacing by month/i)).toBeInTheDocument();
    expect(screen.getByText('2026-03')).toBeInTheDocument();
    expect(screen.getByText('2026-04')).toBeInTheDocument();
    expect(screen.getByText('2026-05')).toBeInTheDocument();
  });
});
