import React from 'react';
import '@testing-library/jest-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import { StructurePageConsolidated } from '../../src/components/zion/StructurePageConsolidated.jsx';

let mockStore = {};
const noop = vi.fn();

vi.mock('../../src/state/identityStore', () => ({
  useIdentityStore: () => mockStore,
}));

function buildStore() {
  const cycleId = 'cycle-1';
  const goalId = 'goal-1';
  return {
    activeCycleId: cycleId,
    cyclesById: {
      [cycleId]: {
        id: cycleId,
        status: 'active',
        goalContract: { goalId, startDayKey: '2026-03-01', endDayKey: '2026-04-01' },
        executionEvents: [],
      },
    },
    goalExecutionContract: { goalId, startDayKey: '2026-03-01', endDayKey: '2026-04-01' },
    aspirations: [],
    appTime: { activeDayKey: '2026-03-10', nowISO: '2026-03-10T12:00:00.000Z', timeZone: 'UTC' },
    proposedBlocks: [
      { id: 'p1', cycleId, goalId, status: 'suggested' },
      { id: 'p2', cycleId, goalId, status: 'suggested' },
    ],
    suggestedBlocks: [],
    lastPlanError: null,
    deliverablesByCycleId: {
      [cycleId]: {
        cycleId,
        autoGenerated: true,
        autoStrategy: { detectedType: 'generic' },
        suggestionLinks: {},
        deliverables: [
          { id: 'd1', title: 'Planning & setup', requiredBlocks: 4 },
          { id: 'd2', title: 'Core production', requiredBlocks: 4 },
          { id: 'd3', title: 'Verification & finalization', requiredBlocks: 4 },
        ],
      },
    },
    goalAdmissionByGoal: {},
    updateWorkWindows: noop,
    attemptGoalAdmission: noop,
  };
}

describe('Structure non-equivalence of sessions and proposed blocks', () => {
  beforeEach(() => {
    mockStore = buildStore();
  });

  it('distinguishes abstract required sessions from proposed calendar blocks', () => {
    render(<StructurePageConsolidated />);
    expect(screen.getByText(/2 proposed calendar blocks/i)).toBeInTheDocument();
    expect(screen.getByText(/plan sections \(3\)/i)).toBeInTheDocument();
    expect(screen.getAllByText(/4 required work sessions/i).length).toBe(3);
    expect(screen.queryByText(/2 blocks proposed/i)).not.toBeInTheDocument();
  });
});
