import { buildGoalIntakeContract } from './src/domain/goal/GoalIntakeContract.ts';
import { generateAutoDeliverables } from './src/core/autoDeliverables.ts';
import { computeDerivedState } from './src/state/identityCompute.js';

const intake = buildGoalIntakeContract({
  goalId: 'goal-st01-ep',
  rawGoalText: 'Finish and release a polished 3-song EP',
  verificationCriteria: '3 songs fully recorded, mixed, mastered, and live on at least 2 streaming platforms',
  executionType: 'CreativeProduction',
  deadline: '2026-05-20',
});

const goalContract = {
  goalId: 'goal-st01-ep',
  goalLabel: 'Finish and release a polished 3-song EP',
  goalText: 'Finish and release a polished 3-song EP',
  goalIntakeContract: intake,
  terminalOutcome: {
    text: 'A polished 3-song EP is recorded, mixed, mastered, and released on streaming platforms',
    verificationCriteria: '3 songs fully recorded, mixed, mastered, and live on at least 2 streaming platforms',
    isConcrete: true,
  },
  deadline: { dayKey: '2026-05-20', isHardDeadline: true },
  startDayKey: '2026-04-05',
  startDateISO: '2026-04-05T00:00:00.000Z',
  executionType: 'CreativeProduction',
  workWindows: {
    mon: [{ start: '18:00', end: '21:00' }],
    tue: [{ start: '18:00', end: '21:00' }],
    wed: [],
    thu: [{ start: '18:00', end: '21:00' }],
    fri: [],
    sat: [{ start: '10:00', end: '14:00' }],
    sun: [{ start: '10:00', end: '14:00' }],
  },
};

const primaryDelivs = generateAutoDeliverables(goalContract);
const totalBlocks = primaryDelivs.reduce((s, d) => s + d.requiredBlocks, 0);
console.log('Total required blocks:', totalBlocks);

// Simulate proposed blocks (one per deliverable to activate plan quality gate)
// Each block inherits the deliverable title
const proposedBlocks = primaryDelivs.flatMap((d, di) =>
  Array.from({ length: d.requiredBlocks }, (_, bi) => ({
    id: `block-${di}-${bi}`,
    title: d.title,
    deliverableId: d.id,
    goalId: 'goal-st01-ep',
    cycleId: 'cycle-st01',
    status: 'suggested',
  }))
);

console.log('Proposed block count:', proposedBlocks.length);
console.log('Sample block titles:');
proposedBlocks.slice(0, 5).forEach(b => console.log(`  "${b.title}"`));

// Build full state and run computeDerivedState
const baseState = {
  today: { date: '2026-04-05', blocks: [], completionRate: 0, driftSignal: 'contained', loadByPractice: {}, practices: [] },
  currentWeek: { weekStart: '2026-04-05', days: [], metrics: {} },
  cycle: [],
  viewDate: '2026-04-05',
  templates: { objectives: {} },
  lastAdaptedDate: null,
  stability: { headline: '', actionLine: '' },
  meta: { version: '1.0.0', onboardingComplete: true },
  recurringPatterns: [],
  lastSessionChange: null,
  nextSuggestion: null,
  executionEvents: [],
  ledger: [],
  aspirations: [],
  aspirationsByCycleId: {},
  cyclesById: {
    'cycle-st01': {
      id: 'cycle-st01',
      status: 'ACTIVE',
      startedAtDayKey: '2026-04-05',
      executionGraphReady: false,
      goalContract,
      actions: [],
      proposedBlocks,
      suggestedBlocks: proposedBlocks,
    },
  },
  cycleOrder: ['cycle-st01'],
  activeCycleId: 'cycle-st01',
  appTime: {
    timeZone: 'UTC',
    nowISO: '2026-04-05T12:00:00.000Z',
    activeDayKey: '2026-04-05',
    isFollowingNow: true,
  },
  constraints: { maxBlocksPerDay: 4, maxBlocksPerWeek: 16 },
  goalAdmissionByGoal: { 'goal-st01-ep': { status: 'ADMITTED' } },
  probabilityByGoal: {},
  feasibilityByGoal: {},
  deliverablesByCycleId: {
    'cycle-st01': { deliverables: primaryDelivs, autoGenerated: true },
  },
};

const next = computeDerivedState(baseState, { type: 'NO_OP' });
const cycle = next.cyclesById['cycle-st01'];

console.log('\n=== PLAN QUALITY GATE ===');
const pqg = cycle?.planQualityGate;
console.log('status:', pqg?.status);
console.log('failureCodes:', JSON.stringify(pqg?.failureCodes));
console.log('meta:', JSON.stringify(pqg?.meta));

console.log('\n=== FEASIBILITY BY GOAL ===');
const feas = next.feasibilityByGoal?.['goal-st01-ep'];
console.log('status:', feas?.status);
console.log('reasons:', JSON.stringify(feas?.reasons));

console.log('\n=== PROBABILITY BY GOAL ===');
const prob = next.probabilityByGoal?.['goal-st01-ep'];
console.log('admissionStatus:', prob?.admissionStatus);
console.log('posScore:', prob?.posScore);
console.log('reasons:', JSON.stringify(prob?.reasons));

console.log('\n=== POLICY STATE ===');
const policy = cycle?.policyState?.goalPolicy;
console.log('intakeReadiness.state:', policy?.intakeReadiness?.state);
console.log('planQuality.state:', policy?.planQuality?.state);
console.log('planQuality.structuralState:', policy?.planQuality?.structuralState);
console.log('planQuality.actionTypeCoverage:', policy?.planQuality?.actionTypeCoverage);
console.log('planQuality.lineageIntegrity:', policy?.planQuality?.lineageIntegrity);
console.log('feasibility.state:', policy?.feasibility?.state);
console.log('feasibility.scheduleFit:', policy?.feasibility?.scheduleFit);
console.log('feasibility.capacitySupport:', policy?.feasibility?.capacitySupport);
console.log('feasibility.structuralSupport:', policy?.feasibility?.structuralSupport);
console.log('feasibility.assumptionBurden:', policy?.feasibility?.assumptionBurden);
console.log('feasibility.reasonCodes:', JSON.stringify(policy?.feasibility?.reasonCodes));
console.log('posTrust.state:', policy?.posTrust?.state);
