export type PlanQualityGateStatus = 'PLAN_QUALITY_PASSED' | 'PLAN_QUALITY_WITHHELD';

export type PlanQualityFailureCode =
  | 'PLAN_COVERAGE_MISSING_MAJOR_COMPONENT'
  | 'PLAN_COVERAGE_MISSING_DELIVERABLE_BRANCH'
  | 'PLAN_COVERAGE_MISSING_EXECUTION_DESCENDANTS'
  | 'PLAN_COVERAGE_PARTIAL_SCOPE_COLLAPSE'
  | 'DELIVERABLE_OBJECT_MISSING'
  | 'DELIVERABLE_TOO_GENERIC'
  | 'DELIVERABLE_GOAL_DISCONNECTED'
  | 'DELIVERABLE_SEMANTIC_HOLLOWNESS'
  | 'ACTION_LINEAGE_BROKEN'
  | 'BLOCK_LINEAGE_BROKEN'
  | 'BLOCK_TOO_GENERIC'
  | 'BLOCK_GOAL_OBJECT_MISSING'
  | 'LINEAGE_VISIBLE_MEANING_LOSS'
  | 'FEASIBILITY_NOT_ADMITTED_PLAN_QUALITY_WITHHELD'
  | 'POS_NOT_ADMITTED_PLAN_QUALITY_WITHHELD'
  | 'POS_NOT_ADMITTED_FEASIBILITY_WITHHELD'
  | 'POS_NOT_ADMITTED_INCOMPLETE_PLAN_SUBSTRATE'
  | 'OUTCOME_COVERAGE_PREP_ONLY'
  | 'OUTCOME_COVERAGE_TERMINAL_STAGE_MISSING'
  | 'OUTCOME_ENDPOINT_MISSING'
  | 'OUTCOME_SPLIT_DIMENSION_UNCOVERED'
  | 'MISSING_OUTCOME_TARGET'
  | 'LONG_HORIZON_TEMPORAL_COMPRESSION'
  | 'LONG_HORIZON_UNJUSTIFIED_TAIL_GAP'
  | 'LONG_HORIZON_SPARSE_CADENCE'
  | 'LONG_HORIZON_WORK_GAPS'
  | 'COMMERCIAL_BLOCK_SPECIFICITY_WEAK'
  | 'COMMERCIAL_WORK_WINDOW_UNDERUSED'
  | 'TERMINAL_OBJECT_DRIFT'
  | 'COMMERCIAL_READINESS_MISSING'
  | 'PURCHASE_PATH_MISSING'
  | 'FIRST_SALES_CORRIDOR_MISSING'
  | 'BRAND_LAUNCH_SUBSTITUTED_FOR_PRODUCT_LAUNCH'
  | 'TERMINAL_EVENT_EVIDENCE_MISSING'
  | 'MISSING_EXECUTION_OWNER'
  | 'MISSING_EXECUTION_DURATION'
  | 'MISSING_EXECUTION_ARTIFACT'
  | 'MISSING_EXECUTION_CONSUMER'
  | 'MISSING_EXECUTION_PASS_EVIDENCE'
  | 'MISSING_GATE_PASS_CRITERIA'
  | 'MISSING_GATE_FAIL_CRITERIA'
  | 'MISSING_GATE_FAILURE_BRANCH'
  | 'MISSING_BD_EXECUTION_MECHANICS'
  | 'MISSING_EXTERNAL_STAKEHOLDER_TOUCHPOINT'
  | 'MISSING_CAPITAL_AMOUNT_OR_BUDGET_RANGE'
  | 'REVIEW_WITHOUT_PRIOR_ARTIFACT'
  | 'EXCESSIVE_REVIEW_AUDIT_RATIO'
  | 'MECHANICAL_CADENCE_LOOP'
  | 'STALE_ACTIVE_CYCLE_STATE'
  | 'ACTIVE_CYCLE_STARTS_IN_PAST_WITHOUT_CONFIRMATION'
  | 'MONITORING_WITHOUT_PRODUCTION'
  | 'MISSING_CONSUMED_BY_REF'
  | 'UNRESOLVED_CONSUMED_BY_REF'
  | 'NON_DOWNSTREAM_CONSUMED_BY_REF'
  | 'PHASE_WITHOUT_EXECUTION_WORK'
  | 'FRONT_LOADED_EXECUTION'
  | 'SPARSE_HORIZON_COVERAGE'
  | 'VAGUE_EXECUTION_ARTIFACT'
  | 'VAGUE_PASS_EVIDENCE'
  | 'FRAGMENTARY_BLOCK_TITLE'
  | 'NON_ACTIONABLE_BLOCK_TITLE'
  | 'QUESTION_BLOCK_TITLE'
  | 'MISSING_PHASE_OBJECTIVE'
  | 'VAGUE_PHASE_OBJECTIVE'
  | 'MISSING_PHASE_UNLOCK_CRITERIA'
  | 'VAGUE_PHASE_UNLOCK_CRITERIA'
  | 'PHASE_OBJECTIVE_WITHOUT_SUPPORTING_BLOCKS'
  | 'PHASE_OBJECTIVE_NOT_MISSION_ALIGNED'
  | 'TERMINAL_OUTCOME_WITHOUT_PHASE_SUPPORT'
  | 'MISSING_LANE_OUTCOME'
  | 'VAGUE_LANE_OUTCOME'
  | 'LANE_WITHOUT_EXECUTION_WORK'
  | 'LANE_OUTCOME_WITHOUT_PHASE_OR_MISSION_SUPPORT'
  | 'BLOCK_DETAIL_AMBIGUOUS'
  | 'GENERIC_EXECUTION_INSTRUCTION'
  | 'LANE_CONTEXT_NOT_APPLIED'
  | 'MISSING_EXPECTED_OUTPUT'
  | 'MISSING_ACCEPTANCE_EVIDENCE'
  | 'MISSING_DEPENDENCY_CONTEXT'
  | 'TITLE_REPEATED_AS_EXPLANATION'
  | 'UNKNOWN_LANE_IDENTITY'
  | 'UNKNOWN_WORK_TYPE'
  | 'TITLE_REPEATED_IN_DO_THIS'
  | 'TITLE_REPEATED_IN_DONE_WHEN'
  | 'TITLE_REPEATED_IN_PRODUCES'
  | 'MISSING_COMPLETED_ARTIFACT'
  | 'ABSTRACT_BLOCK_MEANING'
  | 'INITIATIVE_LABEL_MISSING'
  | 'OUTPUT_ARTIFACT_TOO_VAGUE'
  | 'COMPLETION_STANDARD_TOO_VAGUE'
  | 'INITIATIVE_LABEL_INACCURATE'
  | 'PHASE_PRIORITY_MISCLASSIFIED'
  | 'PREMATURE_INITIATIVE_ACTIVATION'
  | 'USER_DECISION_DUMPING'
  | 'DEFERRED_LANE_SCHEDULED_AS_ACTIVE'
  | 'LONG_HORIZON_LANE_OVERWEIGHTED_IN_P1'
  | 'PHASE_SCOPE_CONFLICT'
  | 'DEFERRED_LANE_SCHEDULED_WITHOUT_JUSTIFICATION'
  | 'FUTURE_PHASE_WORK_REQUIRES_PREREQUISITE_PROOF'
  | 'ACTIVE_BLOCK_UNKNOWN_LANE'
  | 'ACTIVE_BLOCK_UNKNOWN_ENTITY'
  | 'PROJECT_CONTEXT_MISSING'
  | 'ENTITY_PURPOSE_MISMATCH'
  | 'SCHEDULE_DISTRIBUTION_CLUSTER_UNJUSTIFIED'
  | 'P1_NONCRITICAL_LANE_OVERREPRESENTED'
  | 'PHASE_ENERGY_VIOLATION'
  | 'LOW_PRIORITY_WORK_CROWDS_OUT_P1'
  | 'FULL_HORIZON_REPRESENTATION_LEAKED_INTO_SPRINT'
  | 'INTAKE_FACT_CONTRADICTION'
  | 'MILESTONE_RENDERED_AS_EXECUTION_BLOCK'
  | 'PLACEHOLDER_EXECUTION_LANGUAGE'
  | 'GENERIC_PROGRESS_NOTE_ARTIFACT'
  | 'ENTITY_DOCTRINE_UNRESOLVED'
  | 'FEASIBILITY_DEMAND_EXCEEDS_CAPACITY';

export type PlanQualityGateResult = {
  status: PlanQualityGateStatus;
  failureCodes: PlanQualityFailureCode[];
  reasonCodes: string[];
  meta?: {
    missingMajorComponents?: string[];
    missingDeliverableBranches?: string[];
    missingExecutionDescendants?: string[];
    weakDeliverableIds?: string[];
    weakBlockIds?: string[];
    goalDisconnectedDeliverableIds?: string[];
    semanticHollowDeliverableIds?: string[];
    goalObjectMissingBlockIds?: string[];
    meaningLossBlockIds?: string[];
    substanceMissingBlockIds?: string[];
    consumedByRefMissingBlockIds?: string[];
    consumedByRefUnresolvedBlockIds?: string[];
    consumedByRefNonDownstreamBlockIds?: string[];
    phasesWithoutExecution?: string[];
    vagueArtifactBlockIds?: string[];
    vagueEvidenceBlockIds?: string[];
    fragmentaryBlockIds?: string[];
    nonActionableBlockIds?: string[];
    questionBlockIds?: string[];
    phasesWithMissingObjective?: string[];
    phasesWithVagueObjective?: string[];
    phasesWithMissingUnlockCriteria?: string[];
    phasesWithVagueUnlockCriteria?: string[];
    phasesWithoutSupportingBlocks?: string[];
    phasesNotMissionAligned?: string[];
    lanesWithMissingOutcome?: string[];
    lanesWithVagueOutcome?: string[];
    lanesWithoutExecution?: string[];
    lanesWithoutSupport?: string[];
    blockDetailQualityFailures?: Record<string, string[]>;
    temporalDistribution?: {
      contractStartDayKey: string;
      contractEndDayKey: string;
      firstScheduledDayKey: string;
      lastScheduledDayKey: string;
      horizonDays: number;
      scheduledSpanDays: number;
      occupiedMonths: string[];
      latestScheduledHorizonRatio: number;
      requiredLatestHorizonRatio: number;
      requiredOccupiedMonths: number;
      remainingTailDays?: number;
      remainingTailRatio?: number;
      maxUnjustifiedTailRatio?: number;
      scheduledBlockCount?: number;
      averageBlocksPerWeek?: number;
      requiredAverageBlocksPerWeek?: number;
      maxInterBlockGapDays?: number;
      maxAllowedInterBlockGapDays?: number;
      averageActiveWeekdaysPerScheduledWeek?: number;
      requiredActiveWeekdaysPerScheduledWeek?: number;
      clusteredWeekdayLabels?: string[];
      clusteredWeekdayRatio?: number;
      availableWeekdayCount?: number;
    };
    commercialBlockSpecificity?: {
      repeatedShellBlockIds: string[];
      repeatedShellTitleCount: number;
      repeatedShellTitleRatio: number;
      maxRepeatedShellTitleCount: number;
      maxRepeatedShellTitleRatio: number;
    };
    commercialSemanticCoverage?: {
      requiredFamilies: string[];
      coveredFamilies: string[];
      missingFamilies: string[];
      invalidSubstituteFamilies: string[];
      evaluatedArtifacts: number;
    };
  };
};
