export const jobSearchPipelineActions = [
  {
    id: 'prep:001:target-role-map',
    title: 'Define target role map and search criteria',
    deliverable: 'Target role profile with role families locations and compensation bounds',
    definitionOfDone: 'Target criteria finalized with include and exclude role rules.',
    estimateMin: 60,
    dependencies: [],
  },
  {
    id: 'prep:002:resume-portfolio',
    title: 'Tailor resume and portfolio for target roles',
    deliverable: 'Updated resume and portfolio aligned to selected role family',
    definitionOfDone: 'Resume and portfolio validated against five live job descriptions.',
    estimateMin: 120,
    dependencies: ['prep:001:target-role-map'],
  },
  {
    id: 'pipeline:001:company-list',
    title: 'Build prioritized company pipeline list',
    deliverable: 'Ranked target company list with application tracker initialized',
    definitionOfDone: 'Pipeline includes 30 targets with statuses and follow-up dates.',
    estimateMin: 90,
    dependencies: ['prep:002:resume-portfolio'],
  },
  {
    id: 'pipeline:003:application-batch-1',
    title: 'Submit first batch of tailored applications',
    deliverable: 'First batch of 10 tailored applications submitted and logged',
    definitionOfDone: '10 applications submitted with custom notes and tracker updates.',
    estimateMin: 120,
    dependencies: ['pipeline:001:company-list'],
  },
  {
    id: 'interview:002:mock-round',
    title: 'Run mock interview rounds and feedback review',
    deliverable: 'Interview prep packet with feedback actions and STAR story revisions',
    definitionOfDone: 'Two mock rounds complete and remediation actions documented.',
    estimateMin: 90,
    dependencies: ['pipeline:003:application-batch-1'],
  },
];

export const physicalTrainingActions = [
  {
    id: 'baseline:001:assessment',
    title: 'Complete baseline movement and conditioning assessment',
    deliverable: 'Baseline assessment completed with recorded mobility and conditioning metrics',
    definitionOfDone: 'Baseline metrics logged and reviewed for block design.',
    estimateMin: 60,
    dependencies: [],
  },
  {
    id: 'protocol:001:block-one',
    title: 'Execute training block one sessions',
    deliverable: 'Training block one sessions completed and logged with adherence notes',
    definitionOfDone: 'All planned sessions in block one completed and logged.',
    estimateMin: 180,
    dependencies: ['baseline:001:assessment'],
  },
  {
    id: 'benchmark:001:week4-test',
    title: 'Run week-4 benchmark test',
    deliverable: 'Week-4 benchmark completed with performance delta recorded',
    definitionOfDone: 'Benchmark performed and compared against baseline metrics.',
    estimateMin: 60,
    dependencies: ['protocol:001:block-one'],
  },
  {
    id: 'protocol:002:block-two',
    title: 'Execute training block two sessions',
    deliverable: 'Training block two sessions completed with progression targets met',
    definitionOfDone: 'Block two sessions complete with progression metrics documented.',
    estimateMin: 180,
    dependencies: ['benchmark:001:week4-test'],
  },
  {
    id: 'review:001:final',
    title: 'Run final performance review',
    deliverable: 'Final performance review completed with next-cycle recommendation',
    definitionOfDone: 'Final review compares baseline benchmark and target outcome status.',
    estimateMin: 60,
    dependencies: ['protocol:002:block-two'],
  },
];
